/**
 * T34 — C++ scope marker codegen.
 */
import type { AnchorId } from '../types.js';

export function generateCppHeader(enabled: boolean): string {
  if (enabled) {
    // Header-only JSONL recorder. A measurement build emits one TraceEvent per
    // line to the path in $ANATOMIA_TRACE_FILE (recording is OFF when the env var
    // is unset, so a measurement binary can still run without writing a trace).
    // The events match dynamic/protocol.ts exactly so ingest.ts can read them
    // back. Zone markers carry the AnchorId baked in at injection time, so no
    // name→anchor resolution is needed on ingest. Timestamps are steady_clock µs.
    return `#pragma once
// Anatomia measurement instrumentation header.
// Include in translation units compiled with ANATOMIA_MEASUREMENT_BUILD defined.
// Auto-generated by Anatomia (dynamic/inject-cpp.ts) — do not edit by hand.

#ifdef ANATOMIA_MEASUREMENT_BUILD
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <chrono>
#include <mutex>

namespace anatomia {

  // Process-wide JSONL sink. Opened lazily from $ANATOMIA_TRACE_FILE; recording
  // is a no-op when the env var is unset (a measurement build still runs clean).
  class Recorder {
  public:
    static Recorder& instance() { static Recorder r; return r; }

    bool enabled() const { return file_ != nullptr; }

    std::uint64_t nowUs() const {
      using namespace std::chrono;
      return static_cast<std::uint64_t>(
        duration_cast<microseconds>(steady_clock::now().time_since_epoch()).count());
    }

    void frameBegin(std::uint64_t id, std::uint64_t ts) {
      writeEvent("frame_begin", id, ts, nullptr);
    }
    void frameEnd(std::uint64_t id, std::uint64_t ts) {
      writeEvent("frame_end", id, ts, nullptr);
    }
    void zoneEnter(const char* anchorId, std::uint64_t ts) {
      writeZone("zone_enter", anchorId, ts);
    }
    void zoneExit(const char* anchorId, std::uint64_t ts) {
      writeZone("zone_exit", anchorId, ts);
    }

  private:
    std::FILE* file_ = nullptr;
    std::mutex mu_;

    Recorder() {
      const char* path = std::getenv("ANATOMIA_TRACE_FILE");
      if (path && path[0]) file_ = std::fopen(path, "wb");
    }
    ~Recorder() { if (file_) std::fclose(file_); }
    Recorder(const Recorder&) = delete;
    Recorder& operator=(const Recorder&) = delete;

    void writeEvent(const char* type, std::uint64_t frameId, std::uint64_t ts, const char*) {
      if (!file_) return;
      std::lock_guard<std::mutex> lk(mu_);
      std::fprintf(file_, "{\\"type\\":\\"%s\\",\\"frameId\\":%llu,\\"timestampUs\\":%llu}\\n",
                   type, (unsigned long long)frameId, (unsigned long long)ts);
    }
    void writeZone(const char* type, const char* anchorId, std::uint64_t ts) {
      if (!file_) return;
      std::lock_guard<std::mutex> lk(mu_);
      std::fprintf(file_, "{\\"type\\":\\"%s\\",\\"anchorId\\":\\"%s\\",\\"timestampUs\\":%llu}\\n",
                   type, anchorId, (unsigned long long)ts);
    }
  };

  // RAII scope marker: emits zone_enter on construction, zone_exit on destruction.
  struct Zone {
    const char* anchorId;
    explicit Zone(const char* /*name*/, const char* anchorId_) : anchorId(anchorId_) {
      Recorder::instance().zoneEnter(anchorId, Recorder::instance().nowUs());
    }
    ~Zone() {
      Recorder::instance().zoneExit(anchorId, Recorder::instance().nowUs());
    }
  };

} // namespace anatomia

#define ANATOMIA_CONCAT_(a, b) a##b
#define ANATOMIA_CONCAT(a, b) ANATOMIA_CONCAT_(a, b)
#define ANATOMIA_ZONE(name, anchorId) \\
  ::anatomia::Zone ANATOMIA_CONCAT(_anatomia_zone_, __LINE__)(name, anchorId)
// Frame markers go in the game's main loop (Anatomia cannot auto-locate it):
//   ANATOMIA_FRAME_BEGIN(frameIndex); ... ANATOMIA_FRAME_END(frameIndex);
#define ANATOMIA_FRAME_BEGIN(id) \\
  ::anatomia::Recorder::instance().frameBegin((id), ::anatomia::Recorder::instance().nowUs())
#define ANATOMIA_FRAME_END(id) \\
  ::anatomia::Recorder::instance().frameEnd((id), ::anatomia::Recorder::instance().nowUs())
#else
#define ANATOMIA_ZONE(name, anchorId) /* no-op */
#define ANATOMIA_FRAME_BEGIN(id) /* no-op */
#define ANATOMIA_FRAME_END(id) /* no-op */
#endif
`;
  } else {
    return `#pragma once
// Anatomia measurement instrumentation header (disabled).
// Compile with ANATOMIA_MEASUREMENT_BUILD to enable zone + frame markers.

#define ANATOMIA_ZONE(name, anchorId) /* no-op */
#define ANATOMIA_FRAME_BEGIN(id) /* no-op */
#define ANATOMIA_FRAME_END(id) /* no-op */
`;
  }
}

export interface DomainEntryPoint {
  filePath: string;
  line: number;
  anchorId: AnchorId;
  name: string;
}

export interface InjectionPatch {
  filePath: string;
  line: number;
  code: string;
}

export function generateCppPatches(entryPoints: DomainEntryPoint[]): InjectionPatch[] {
  return entryPoints.map((ep) => ({
    filePath: ep.filePath,
    line: ep.line,
    code: `ANATOMIA_ZONE("${ep.name}", "${ep.anchorId}");`,
  }));
}
