/**
 * T34 — C++ scope marker codegen.
 */
import type { AnchorId, AstNode, FunctionNode } from '../types.js';

export function generateCppHeader(enabled: boolean): string {
  if (enabled) {
    // Header-only JSONL recorder. A measurement build emits one TraceEvent per
    // line to the path in $ANATOMIA_TRACE_FILE (recording is OFF when the env var
    // is unset, so a measurement binary can still run without writing a trace).
    // The events match dynamic/protocol.ts exactly so ingest.ts can read them
    // back. Zone markers carry the AnchorId baked in at injection time, so no
    // name→anchor resolution is needed on ingest. Timestamps are steady_clock µs.
    return `#pragma once
// Anatomia measurement instrumentation header.
// Include in translation units compiled with ANATOMIA_MEASUREMENT_BUILD defined.
// Auto-generated by Anatomia (dynamic/inject-cpp.ts) — do not edit by hand.

#ifdef ANATOMIA_MEASUREMENT_BUILD
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <chrono>
#include <mutex>

namespace anatomia {

  // Process-wide JSONL sink. Opened lazily from $ANATOMIA_TRACE_FILE; recording
  // is a no-op when the env var is unset (a measurement build still runs clean).
  class Recorder {
  public:
    static Recorder& instance() { static Recorder r; return r; }

    bool enabled() const { return file_ != nullptr; }

    std::uint64_t nowUs() const {
      using namespace std::chrono;
      return static_cast<std::uint64_t>(
        duration_cast<microseconds>(steady_clock::now().time_since_epoch()).count());
    }

    void frameBegin(std::uint64_t id, std::uint64_t ts) {
      writeEvent("frame_begin", id, ts, nullptr);
    }
    void frameEnd(std::uint64_t id, std::uint64_t ts) {
      writeEvent("frame_end", id, ts, nullptr);
    }
    void zoneEnter(const char* anchorId, std::uint64_t ts) {
      writeZone("zone_enter", anchorId, ts);
    }
    void zoneExit(const char* anchorId, std::uint64_t ts) {
      writeZone("zone_exit", anchorId, ts);
    }

  private:
    std::FILE* file_ = nullptr;
    std::mutex mu_;

    Recorder() {
      const char* path = std::getenv("ANATOMIA_TRACE_FILE");
      if (path && path[0]) file_ = std::fopen(path, "wb");
    }
    ~Recorder() { if (file_) std::fclose(file_); }
    Recorder(const Recorder&) = delete;
    Recorder& operator=(const Recorder&) = delete;

    void writeEvent(const char* type, std::uint64_t frameId, std::uint64_t ts, const char*) {
      if (!file_) return;
      std::lock_guard<std::mutex> lk(mu_);
      std::fprintf(file_, "{\\"type\\":\\"%s\\",\\"frameId\\":%llu,\\"timestampUs\\":%llu}\\n",
                   type, (unsigned long long)frameId, (unsigned long long)ts);
    }
    void writeZone(const char* type, const char* anchorId, std::uint64_t ts) {
      if (!file_) return;
      std::lock_guard<std::mutex> lk(mu_);
      std::fprintf(file_, "{\\"type\\":\\"%s\\",\\"anchorId\\":\\"%s\\",\\"timestampUs\\":%llu}\\n",
                   type, anchorId, (unsigned long long)ts);
    }
  };

  // RAII scope marker: emits zone_enter on construction, zone_exit on destruction.
  struct Zone {
    const char* anchorId;
    explicit Zone(const char* /*name*/, const char* anchorId_) : anchorId(anchorId_) {
      Recorder::instance().zoneEnter(anchorId, Recorder::instance().nowUs());
    }
    ~Zone() {
      Recorder::instance().zoneExit(anchorId, Recorder::instance().nowUs());
    }
  };

} // namespace anatomia

#define ANATOMIA_CONCAT_(a, b) a##b
#define ANATOMIA_CONCAT(a, b) ANATOMIA_CONCAT_(a, b)
#define ANATOMIA_ZONE(name, anchorId) \\
  ::anatomia::Zone ANATOMIA_CONCAT(_anatomia_zone_, __LINE__)(name, anchorId)
// Frame markers go in the game's main loop (Anatomia cannot auto-locate it):
//   ANATOMIA_FRAME_BEGIN(frameIndex); ... ANATOMIA_FRAME_END(frameIndex);
#define ANATOMIA_FRAME_BEGIN(id) \\
  ::anatomia::Recorder::instance().frameBegin((id), ::anatomia::Recorder::instance().nowUs())
#define ANATOMIA_FRAME_END(id) \\
  ::anatomia::Recorder::instance().frameEnd((id), ::anatomia::Recorder::instance().nowUs())
#else
#define ANATOMIA_ZONE(name, anchorId) /* no-op */
#define ANATOMIA_FRAME_BEGIN(id) /* no-op */
#define ANATOMIA_FRAME_END(id) /* no-op */
#endif
`;
  } else {
    return `#pragma once
// Anatomia measurement instrumentation header (disabled).
// Compile with ANATOMIA_MEASUREMENT_BUILD to enable zone + frame markers.

#define ANATOMIA_ZONE(name, anchorId) /* no-op */
#define ANATOMIA_FRAME_BEGIN(id) /* no-op */
#define ANATOMIA_FRAME_END(id) /* no-op */
`;
  }
}

export interface DomainEntryPoint {
  filePath: string;
  line: number;
  anchorId: AnchorId;
  name: string;
}

export interface InjectionPatch {
  filePath: string;
  line: number;
  code: string;
}

export function generateCppPatches(entryPoints: DomainEntryPoint[]): InjectionPatch[] {
  return entryPoints.map((ep) => ({
    filePath: ep.filePath,
    line: ep.line,
    code: `ANATOMIA_ZONE("${ep.name}", "${ep.anchorId}");`,
  }));
}

// ---------------------------------------------------------------------------
// Frame-marker auto-detection (#347)
// ---------------------------------------------------------------------------

/** Heuristic function names that identify a game's main loop. */
const MAIN_LOOP_HEURISTIC_NAMES = new Set<string>([
  "main", "run", "Run", "loop", "Loop",
  "gameLoop", "GameLoop", "mainLoop", "MainLoop", "tick",
]);

/**
 * Source location of a detected main-loop function, with frame-marker
 * insertion lines pre-computed for ANATOMIA_FRAME_BEGIN / FRAME_END.
 */
export interface MainLoopCandidate {
  filePath: string;
  /** 0-based source line for ANATOMIA_FRAME_BEGIN insertion. */
  frameBeginLine: number;
  /** 0-based source line for ANATOMIA_FRAME_END insertion (before closing brace). */
  frameEndLine: number;
  name: string;
  anchorId: AnchorId;
  /**
   * "loop-body" — frame markers target the inner while/for body (precise);
   * "function"  — fallback to function-boundary lines when no loop is found.
   */
  precision: "loop-body" | "function";
}

/**
 * Scan a function body AST for its first top-level loop statement and return
 * the loop body's source range. Returns null when no while/for loop is found.
 */
function findTopLoopBounds(
  bodyNode: AstNode,
): { startLine: number; endLine: number } | null {
  for (let i = 0; i < bodyNode.childCount; i++) {
    const child = bodyNode.child(i);
    if (!child) continue;
    const t = child.type;
    if (
      t === "while_statement" ||
      t === "for_statement" ||
      t === "for_range_loop" ||
      t === "do_statement"
    ) {
      const body = child.childForFieldName("body");
      if (body) {
        return { startLine: body.startPosition.row, endLine: body.endPosition.row };
      }
    }
  }
  return null;
}

/**
 * Detect main-loop candidate functions from the analyzed function list.
 *
 * Pass `mainLoopHint` (a function name, case-insensitive) to identify the
 * main loop explicitly; omit it to fall back to the heuristic name set
 * (`main`, `run`, `loop`, `tick`, etc.).
 *
 * For each candidate, the function's body AST is scanned for a top-level
 * while/for loop so that frame markers land at the loop body boundaries
 * (precision = "loop-body"). When no inner loop is found the function's own
 * source boundaries are used as a fallback (precision = "function").
 */
export function detectMainLoopCandidates(
  functions: FunctionNode[],
  mainLoopHint?: string,
): MainLoopCandidate[] {
  const isCandidate = mainLoopHint
    ? (fn: FunctionNode) => {
        const hint = mainLoopHint.toLowerCase();
        const name = fn.name.toLowerCase();
        return name === hint || name.endsWith(`::${hint}`);
      }
    : (fn: FunctionNode) => MAIN_LOOP_HEURISTIC_NAMES.has(fn.name);

  return functions
    .filter((fn) => fn.id !== null && isCandidate(fn))
    .map((fn) => {
      const loop = findTopLoopBounds(fn.bodyAst);
      if (loop) {
        return {
          filePath: fn.sourceRange.filePath,
          frameBeginLine: loop.startLine + 1,
          frameEndLine: loop.endLine,
          name: fn.name,
          anchorId: fn.id!,
          precision: "loop-body" as const,
        };
      }
      return {
        filePath: fn.sourceRange.filePath,
        frameBeginLine: fn.sourceRange.start.line + 1,
        frameEndLine: fn.sourceRange.end.line,
        name: fn.name,
        anchorId: fn.id!,
        precision: "function" as const,
      };
    });
}

/**
 * Generate ANATOMIA_FRAME_BEGIN / FRAME_END injection patches for main-loop
 * candidates detected by `detectMainLoopCandidates`. Returns two patches per
 * candidate (begin + end), suitable for the same patch-apply pipeline as
 * `generateCppPatches`.
 */
export function generateFrameMarkerPatches(candidates: MainLoopCandidate[]): InjectionPatch[] {
  const patches: InjectionPatch[] = [];
  for (const c of candidates) {
    patches.push(
      {
        filePath: c.filePath,
        line: c.frameBeginLine,
        code: `ANATOMIA_FRAME_BEGIN(/*frameId*/0); /* auto:${c.precision} */`,
      },
      {
        filePath: c.filePath,
        line: c.frameEndLine,
        code: `ANATOMIA_FRAME_END(/*frameId*/0); /* auto:${c.precision} */`,
      },
    );
  }
  return patches;
}
