export { classifyProgramModules } from "./classify.js";
export { isDependencyArtifactPath } from "./deps.js";
export { loadProgramDomainConfig } from "./config.js";
export { loadProgramDomainConfigWithPresence } from "./config.js";
export type { LoadedProgramDomainConfig } from "./config.js";
export { deriveProgramDomains } from "./derive.js";
export { layerGlobMatches, layerOfPath } from "./layer-paths.js";
export { BUILTIN_LAYERS, buildLayerPolicy, knownLayerNames, validateLayerDeclaration } from "./layer-policy.js";
export type { LayerPolicy } from "./layer-policy.js";
export { buildProgramDomainInputs, diagnoseProgramDomains } from "./diagnose.js";
export type { ProgramDomainDiagnosis, ProgramDomainInputs, ProgramLayerSummary, ProgramModuleClassification, ProgramUnclassifiedModule } from "./diagnose.js";
export type { ClassifiedModule, ProgramDiagnostic, ProgramDomain, ProgramDomainConfig, ProgramDomainGraph, ProgramLayerRule, ProgramSymbol } from "./types.js";
